Fix crash in acquiring credentials
gssapi/gss-ntlmssp pull request #41
Opened 2020-09-23 14:47 UTC by simo5

When a creedntial store is provide but no name is provided we end up
crashing by dereferencing the name.

Allow the request to proceed without a name, as it may be selected out
of a credential file, but if none was found, return an error.

Fixes #40

2020-09-23 18:21 UTC, frozencemetery requested changes
Typo in commit message - "creedntial"

2020-09-23 18:56 UTC, simo5 commented on src/gss_creds.c
> +        free(cred->cred.user.user.data.user.domain);
I realized that we were leaking memory her as I analyzed the code path so elected to fix it all in one go.

2020-09-25 15:23 UTC, simo5 commented
@frozencemetery the changes have been QAd by @kvv81 (see comment in #41), so they are redy for final review.

2020-09-25 17:53 UTC, frozencemetery approved these changes

2020-09-25 21:10 UTC, merged